version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: 2601
      MYSQL_DATABASE: my_diary
      MYSQL_USER: root
      MYSQL_PASSWORD: 2601
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
